# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chehadeh/multithread_pattern

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chehadeh/multithread_pattern

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chehadeh/multithread_pattern/CMakeFiles /home/chehadeh/multithread_pattern/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chehadeh/multithread_pattern/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multi_thread_app

# Build rule for target.
multi_thread_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_thread_app
.PHONY : multi_thread_app

# fast build rule for target.
multi_thread_app/fast:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/build
.PHONY : multi_thread_app/fast

MsgEmitter.o: MsgEmitter.cpp.o

.PHONY : MsgEmitter.o

# target to build an object file
MsgEmitter.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgEmitter.cpp.o
.PHONY : MsgEmitter.cpp.o

MsgEmitter.i: MsgEmitter.cpp.i

.PHONY : MsgEmitter.i

# target to preprocess a source file
MsgEmitter.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgEmitter.cpp.i
.PHONY : MsgEmitter.cpp.i

MsgEmitter.s: MsgEmitter.cpp.s

.PHONY : MsgEmitter.s

# target to generate assembly for a file
MsgEmitter.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgEmitter.cpp.s
.PHONY : MsgEmitter.cpp.s

MsgReceiver.o: MsgReceiver.cpp.o

.PHONY : MsgReceiver.o

# target to build an object file
MsgReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgReceiver.cpp.o
.PHONY : MsgReceiver.cpp.o

MsgReceiver.i: MsgReceiver.cpp.i

.PHONY : MsgReceiver.i

# target to preprocess a source file
MsgReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgReceiver.cpp.i
.PHONY : MsgReceiver.cpp.i

MsgReceiver.s: MsgReceiver.cpp.s

.PHONY : MsgReceiver.s

# target to generate assembly for a file
MsgReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/MsgReceiver.cpp.s
.PHONY : MsgReceiver.cpp.s

PositionMsg.o: PositionMsg.cpp.o

.PHONY : PositionMsg.o

# target to build an object file
PositionMsg.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/PositionMsg.cpp.o
.PHONY : PositionMsg.cpp.o

PositionMsg.i: PositionMsg.cpp.i

.PHONY : PositionMsg.i

# target to preprocess a source file
PositionMsg.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/PositionMsg.cpp.i
.PHONY : PositionMsg.cpp.i

PositionMsg.s: PositionMsg.cpp.s

.PHONY : PositionMsg.s

# target to generate assembly for a file
PositionMsg.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/PositionMsg.cpp.s
.PHONY : PositionMsg.cpp.s

Reference.o: Reference.cpp.o

.PHONY : Reference.o

# target to build an object file
Reference.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Reference.cpp.o
.PHONY : Reference.cpp.o

Reference.i: Reference.cpp.i

.PHONY : Reference.i

# target to preprocess a source file
Reference.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Reference.cpp.i
.PHONY : Reference.cpp.i

Reference.s: Reference.cpp.s

.PHONY : Reference.s

# target to generate assembly for a file
Reference.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Reference.cpp.s
.PHONY : Reference.cpp.s

ReferenceMessage.o: ReferenceMessage.cpp.o

.PHONY : ReferenceMessage.o

# target to build an object file
ReferenceMessage.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/ReferenceMessage.cpp.o
.PHONY : ReferenceMessage.cpp.o

ReferenceMessage.i: ReferenceMessage.cpp.i

.PHONY : ReferenceMessage.i

# target to preprocess a source file
ReferenceMessage.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/ReferenceMessage.cpp.i
.PHONY : ReferenceMessage.cpp.i

ReferenceMessage.s: ReferenceMessage.cpp.s

.PHONY : ReferenceMessage.s

# target to generate assembly for a file
ReferenceMessage.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/ReferenceMessage.cpp.s
.PHONY : ReferenceMessage.cpp.s

TimedBlock.o: TimedBlock.cpp.o

.PHONY : TimedBlock.o

# target to build an object file
TimedBlock.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/TimedBlock.cpp.o
.PHONY : TimedBlock.cpp.o

TimedBlock.i: TimedBlock.cpp.i

.PHONY : TimedBlock.i

# target to preprocess a source file
TimedBlock.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/TimedBlock.cpp.i
.PHONY : TimedBlock.cpp.i

TimedBlock.s: TimedBlock.cpp.s

.PHONY : TimedBlock.s

# target to generate assembly for a file
TimedBlock.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/TimedBlock.cpp.s
.PHONY : TimedBlock.cpp.s

Timer.o: Timer.cpp.o

.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i

.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s

.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/main.cpp.s
.PHONY : main.cpp.s

thread_initial_unit.o: thread_initial_unit.cpp.o

.PHONY : thread_initial_unit.o

# target to build an object file
thread_initial_unit.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_initial_unit.cpp.o
.PHONY : thread_initial_unit.cpp.o

thread_initial_unit.i: thread_initial_unit.cpp.i

.PHONY : thread_initial_unit.i

# target to preprocess a source file
thread_initial_unit.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_initial_unit.cpp.i
.PHONY : thread_initial_unit.cpp.i

thread_initial_unit.s: thread_initial_unit.cpp.s

.PHONY : thread_initial_unit.s

# target to generate assembly for a file
thread_initial_unit.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_initial_unit.cpp.s
.PHONY : thread_initial_unit.cpp.s

thread_terminal_unit.o: thread_terminal_unit.cpp.o

.PHONY : thread_terminal_unit.o

# target to build an object file
thread_terminal_unit.cpp.o:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_terminal_unit.cpp.o
.PHONY : thread_terminal_unit.cpp.o

thread_terminal_unit.i: thread_terminal_unit.cpp.i

.PHONY : thread_terminal_unit.i

# target to preprocess a source file
thread_terminal_unit.cpp.i:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_terminal_unit.cpp.i
.PHONY : thread_terminal_unit.cpp.i

thread_terminal_unit.s: thread_terminal_unit.cpp.s

.PHONY : thread_terminal_unit.s

# target to generate assembly for a file
thread_terminal_unit.cpp.s:
	$(MAKE) -f CMakeFiles/multi_thread_app.dir/build.make CMakeFiles/multi_thread_app.dir/thread_terminal_unit.cpp.s
.PHONY : thread_terminal_unit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... multi_thread_app"
	@echo "... edit_cache"
	@echo "... MsgEmitter.o"
	@echo "... MsgEmitter.i"
	@echo "... MsgEmitter.s"
	@echo "... MsgReceiver.o"
	@echo "... MsgReceiver.i"
	@echo "... MsgReceiver.s"
	@echo "... PositionMsg.o"
	@echo "... PositionMsg.i"
	@echo "... PositionMsg.s"
	@echo "... Reference.o"
	@echo "... Reference.i"
	@echo "... Reference.s"
	@echo "... ReferenceMessage.o"
	@echo "... ReferenceMessage.i"
	@echo "... ReferenceMessage.s"
	@echo "... TimedBlock.o"
	@echo "... TimedBlock.i"
	@echo "... TimedBlock.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... thread_initial_unit.o"
	@echo "... thread_initial_unit.i"
	@echo "... thread_initial_unit.s"
	@echo "... thread_terminal_unit.o"
	@echo "... thread_terminal_unit.i"
	@echo "... thread_terminal_unit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

